name: Build Addon

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle (NO WRAPPER NEEDED)
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: gradle clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: addon
          path: build/libs/*.jar
